[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.gz"
  [headers.values]
    Content-Type = "application/gzip"
    Content-Encoding = "gzip"
    Access-Control-Allow-Origin = "*"
